Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> > Patch Set 1:
> > 
> > > Patch Set 1:
> > > 
> > > Morgan do you think you could rebase this over https://gerrit.onap.org/r/c/testsuite/heatbridge/+/103240 (58bf891dffae71a766a89910e6fb01703faae8fa) so this change is validated with updated tox setup?
> > 
> > yep
> 
> struggling with gerrit...not able yet to get the patch for a rebase

every time I try to rebase I got an error due to the fact that some patches are closed...
remote: Processing changes: (\)
remote: Processing changes: (|)
remote: Processing changes: (/)
remote: Processing changes: refs: 1 (/)
remote: Processing changes: refs: 1, done            
To ssh://gerrit.onap.org:29418/testsuite/heatbridge.git
 ! [remote rejected] HEAD -> refs/for/master%topic=96474 (change https://gerrit.onap.org/r/c/testsuite/heatbridge/+/96473 closed)
error: failed to push some refs to 'ssh://mrichomme@gerrit.onap.org:29418/testsuite/heatbridge.git'

I am on the patch branch, I just try to rebase El Alto on it
but then the patch ref is a patch from master (96473).. 

I will raise a ticket to LF

Patch-set: 1